// <auto-generated />
namespace StudentAPI.Migrations.StudentMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StudentCreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StudentCreate));
        
        string IMigrationMetadata.Id
        {
            get { return "201710102327049_StudentCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
